name = "Toastys Create"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a94bc3a16031d4ff0ba018c89795c29874ad9bbdef011239e42f046de72a6a1f"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
